### ISSUE TITLE
Battery maintain 無法使用

### ISSUE THREAD

**Issue by Levi609** [js4jiang5/BatteryOptimizer_for_MAC#11]
![image](https://github.com/user-attachments/assets/82899224-3112-4577-a381-f0de7f9c5ffe)

**What is the issue? (required)**
升級到 V2.0.7 之後，battery maintain 會發生問題。
battery maintain 可以使用，battery maintain stop、battery maintain recover、battery maintain 80 30 這些不能使用
作業環境是 M2 MBA macOS Sequoia 15.1

再麻煩您確認，謝謝。

**Comment by js4jiang5** [comment]
了解，這是因為驗證指令是否正確的功能少加入了一些，導致某些功能無法執行，在v2.0.8已修正
