### ISSUE TITLE
Question about Magsafe LED color 

### ISSUE THREAD

**Issue by blazers08** [js4jiang5/BatteryOptimizer_for_MAC#14]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/765ed4c6-4a24-440d-a92c-3b1b1372a7f8">

想問的就是，依照原本apple設定在充電的時候，megasafe LED燈號應該是橘色而不是綠色吧

所以我想這邊應該是要改成 

Setting magsafe color to **_orange_**

setting LED to **_orange_**

當電池充到100%或是到達預設的%數，燈號才是green

依照現在燈號指示，看到綠燈會以為充飽。但實際上正在充電中

**Comment by js4jiang5** [comment]
的確。會這樣顯示是因為放電到達目標時的當下是沒有在充電的，所以顯示綠燈。不過燈號不影響功能，我下版再做修改，謝謝你幫忙找到一個 bug。

**Comment by blazers08** [comment]
應該已經在最新版(2.0.13)修正了，我就closed了，感謝！
