### ISSUE TITLE
Query on how to delete the files

### ISSUE THREAD

**Issue by aoshendev** [js4jiang5/BatteryOptimizer_for_MAC#15]
**Your macbook model and year:**
MacBook Air M3
**Your version number: (run "battery version" to find out)**
v2.0.13

**Your battery status: (run "battery status" to find out)**

12/06/24-01:06:04 - Battery at 94.8%, 12.758V, 31.3°C, no charging
12/06/24-01:06:04 - Battery health 87.6%, Cycle 51
12/06/24-01:06:04 - Your battery is currently being maintained at 80% with sailing to 75%
12/06/24-01:06:04 - You haven't scheduled calibration yet

**What is the issue?**

- It does a good job overall except that when I am trying to discharge while charging, the battery display on the status bar does not change. I am trying to delete it using  `battery uninstall`, the status of the battery is recovered but I found that the battery command still works in the terminal. Could you help me on how to wipe it out from my disk?

- Why the battery status is different from what should in the settings:
<img width="474" alt="image" src="https://github.com/user-attachments/assets/ee74dc75-bcb9-4be0-9f5f-b6c93392bf30">

**Error logs: (run "battery logs" to find out)**
12/06/24-00:59:44 - 🔼🪫 Disabling battery discharging
12/06/24-00:59:45 - 🔌🔋 Enabling battery charging
12/06/24-00:59:47 - 🔼🪫 Disabling battery discharging

**Comment by js4jiang5** [comment]
The capacity Apple shows is 2~7 percent higher than real one. Mine is same with another famous app called coconutBattery.

I have some doubts about your first question.
1. The status shows "no charging", why did you say you were trying to discharge while charging? What commands did you use to result in the condition
2. According to the logs, the status changes from disable discharging/ enable charging/ disable discharging within 3 seconds. Again, what commands did you use to make it happen?
3. All files are supposed to be completely removed when you run "battery uninstall". Could you check if /usr/local/bin/battery still exist? If it's already gone, try to open another terminal and run the command and see what happens.

**Comment by aoshendev** [comment]
Hi,

Thanks very much, my problem is solved.

Awaiting your new updates!
