### ISSUE TITLE
Calibration failed

### ISSUE THREAD

**Issue by sdeviljr** [js4jiang5/BatteryOptimizer_for_MAC#2]
**What is the issue? (required)**
battery calibrate discharging completed at 15% and error happened.
It shows
"Calibration Error: Discharge to 15% fail
Recover in 5 secs, wait ...
Battery maintain is recovered"
I didn't know it will keep doing its job or I need to calibrate again so I tried "battery calibrate" again but 
it also failed this time.
I tried to calibrate third time while playing World of warcraft, my MacBook Pro M1 max 14' 2021 suddenly shutdown.

**What exactly did you do to produce the issue? (required)**
1. battery calibrate

**Expected behavior (required)**
Discharge to 15%, charge to 100% and keep it an hour, than back to my % setting(75%)

**Screenshots (optional)**
None.

**Error logs**
None.

**Additional context (optional)**

**Comment by js4jiang5** [comment]
@sdeviljr It seems that the discharge process was interrupted and exit, meaning that process was killed for some reason. What is the real battery percentage when the error occurred? Had it ever started discharge? Could you tried to calibrate without playing the game and see what happened?

**Comment by sdeviljr** [comment]
The second time calibrated without playing game but still failed.

**Comment by js4jiang5** [comment]
Please update to the latest verion using command "battery update" in Terminal.
If the error still occurs, please let me know what percentage the battery level is when the error message shows up.
