### ISSUE TITLE
While battery calibration, enter `battery status` in another terminal result in illegal time format

### ISSUE THREAD

**Issue by RaymondJSu** [js4jiang5/BatteryOptimizer_for_MAC#8]
I am not sure anyone would do this, but I found out that after discharging the battery to 15% and re-enabling charging, running the `battery status` command in another terminal results in an illegal time format error.

<img width="1473" alt="battery status date conversion error" src="https://github.com/user-attachments/assets/11f3307c-caf4-4371-bfbb-5a0ae4641e8c">

**Comment by js4jiang5** [comment]
Have you update to v2.0.7?
I fixed a date interpretation bug in v2.0.6

**Comment by js4jiang5** [comment]
Another thing that I noticed is that your battery dropped down to 13% after charging starts from 15%. That behavior is not what I expected.

**Comment by RaymondJSu** [comment]
> I fixed a date interpretation bug in v2.0.6
will try again on my next battery calibration

> battery dropped down to 13% after charging starts from 15%.
I believe the reason is that I continued using the laptop while not connected to the power. when it's 13% then I reconnected the power.
