### ISSUE TITLE
升級到 2.0.7 出現的狀況

### ISSUE THREAD

**Issue by swallowcc** [js4jiang5/BatteryOptimizer_for_MAC#9]
你好，以下是剛剛從 2.0.3 升級到 2.0.7 的部分 Log，
有看到一個 command not found 跟一個 Error，不確定是否異常，提供上來讓你參考。

使用機型是 M1 pro, OS 版本是 sequoia 15.0.1.

❯ battery update
This will run curl -sS https://raw.githubusercontent.com/js4jiang5/BatteryOptimizer_for_MAC/main/update.sh | bash
Press any key to continue

🔋 Starting battery update

[ 1 ] Downloading latest battery version
[ 2 ] Writing script to /usr/local/bin/battery
[ 3 ] Setup for power limit when Macs shutdown
Password:
bash: line 111: valid_day: command not found

11/02/24-13:01:11 - 電池自動校正時程安排在 1    日 3:00 開始
11/02/24-13:01:11 - 下次校正日期是 2024/12/01

[ 3 ] Setting up visudo declarations
Error: Unknown command 'visudo'
Did you mean one of these?
Run 'battery' without parameters, for list of valid commands.
[ Final ] Removed temporary folder

🎉 Battery tool updated.

Restarting battery maintain.

* 以下是在 2.0.3 版時設定的排程。
valid_day 猜測是我原本設定的排程無法被讀到或其他因素？
所以升級後直接幫我改日期到 2024/12/01 了。

❯ battery status

11/02/24-13:00:37 - 電池目前 79.1%, 12.073V, 34.2°C, 暫停充電
11/02/24-13:00:37 - 電池健康度 87.4%, 循環次數 114
11/02/24-13:00:37 - 您的電池最佳化維持在 80% 滑行至 30%
11/02/24-13:00:37 - 電池自動校正時程安排在 28    日 3:00 開始
11/02/24-13:00:37 - 下次校正日期是 2024/11/28

**Comment by RaymondJSu** [comment]
謝謝回報, 應該修好了!
